# Generated by Django 4.1.7 on 2024-03-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
