# Generated by Django 4.1.7 on 2024-03-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='user',
            new_name='Rider',
        ),
    ]
