# Generated by Django 4.2.11 on 2024-03-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_rename_user_ride_rider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
