# Generated by Django 4.2.11 on 2024-03-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='Rider',
            new_name='rider',
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='started', max_length=255),
        ),
    ]
