# Generated by Django 4.2.11 on 2024-03-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_rename_rider_ride_rider_alter_ride_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='rider',
            new_name='Rider',
        ),
    ]
