# Generated by Django 4.1.7 on 2024-03-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_rename_rider_ride_rider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subzone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zonename', models.CharField(max_length=255)),
                ('pincode', models.BigIntegerField()),
            ],
        ),
    ]
